services:
  wiremock:
    image: "wiremock/wiremock:latest"
    container_name: wiremock_container
    ports:
      - 8080:8080
    volumes:
      - ./extensions:/var/wiremock/extensions
      - ./__files:/home/wiremock/__files
      - ./mappings:/home/wiremock/mappings
    entrypoint: ["/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose"]
